### ISSUE TITLE
0.4.3 issue which may be simple to solve but has me mystified.

### ISSUE THREAD

**Issue by ErnestRider** [korma/Korma#383]
0.4.2 this runs fine:

tid (:id (first (k/select ResourceType (k/where {:type_name rt}))))

0.4.3 this falls apart

Exception in thread "main" java.lang.IllegalArgumentException: No value supplied for key: {:identifiers #object[clojure.core$identity 0xdc7b462 "clojure.core$identity@dc7b462"]}, compiling:(/private/var/folders/c_/bm7ylmrn5936_1d5s8gh2__c0000gq/T/form-init372197876745126400.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No value supplied for key: {:identifiers #object[clojure.core$identity 0xdc7b462 "clojure.core$identity@dc7b462"]}
	at clojure.lang.PersistentHashMap.create(PersistentHashMap.java:77)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:702)
	at clojure.java.jdbc$query.doInvoke(jdbc.clj:702)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at korma.db$exec_sql.invokeStatic(db.clj:271)
	at korma.db$exec_sql.invoke(db.clj:267)
	at korma.db$do_query.invokeStatic(db.clj:285)
	at korma.db$do_query.invoke(db.clj:283)
	at korma.core$exec.invokeStatic(core.clj:498)
	at korma.core$exec.invoke(core.clj:477)
	at toscana.resource$get_resource_type_id.invokeStatic(resource.clj:54)
	at toscana.resource$get_resource_type_id.invoke(resource.clj:51)
	at toscana.resource$create_resource.invokeStatic(resource.clj:65)
	at toscana.resource$create_resource.invoke(resource.clj:63)
	at toscana.resource$create_resource_id.invokeStatic(resource.clj:71)
	at toscana.resource$create_resource_id.invoke(resource.clj:69)
	at dbmigrate.test$_main.invokeStatic(test.clj:13)
	at dbmigrate.test$_main.doInvoke(test.clj:11)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invokeStatic(form-init372197876745126400.clj:1)
	at user$eval5.invoke(form-init372197876745126400.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
eriders-iMac:dbmigrate erider$

**Comment by venantius** [comment]
I'm going through old issues and trying to clean them up. Has this issue persisted?

If there hasn't been a response to this issue in 2 weeks, I'll close the ticket.

**Comment by thoersch** [comment]
@venantius I too am getting this. Anything > 4.2 including the RC.
